name       : unbound
version    : 1.6.8
release    : 2
source     :
    - https://www.unbound.net/downloads/unbound-1.6.8.tar.gz : e3b428e33f56a45417107448418865fe08d58e0e7fea199b855515f60884dd49
license    : BSD-3-Clause
component  : network.util
summary    : Unbound is a validating, recursive, and caching DNS resolver.
description: |
    Unbound is a validating, recursive, and caching DNS resolver.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %configure --disable-static \
        --enable-pie \
        --enable-relro-now \
        --enable-systemd \
        --enable-ipsecmod \
        --with-libevent \
        --with-conf-file=%libdir%/unbound/unbound.conf \
        --with-pidfile=/run/unbound/unbound.pid
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 contrib/unbound.{service,socket} -t $installdir/%libdir%/systemd/system
    install -Dm00644 contrib/libunbound.pc -t $installdir/%libdir%/pkgconfig
    install -Dm00644 $pkgfiles/unbound.tmpfiles $installdir/%libdir%/tmpfiles.d/unbound.conf
    install -Dm00644 $pkgfiles/unbound.sysusers $installdir/%libdir%/sysusers.d/unbound.conf
check      : |
    %make check
