name       : unbound
version    : 1.6.3
release    : 1
source     :
    - https://www.unbound.net/downloads/unbound-1.6.3.tar.gz : 4c7e655c1d0d2d133fdeb81bc1ab3aa5c155700f66c9f5fb53fa6a5c3ea9845f
license    : BSD-3-Clause
component  : network.util
summary    : Unbound is a validating, recursive, and caching DNS resolver.
description: |
    Unbound is a validating, recursive, and caching DNS resolver.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
